default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

#production:
#  <<: *default
#  database: db/production.sqlite3

production:
  adapter: postgresql
  username: gmrind
  password: gmrind
  database: onlineforms
  port: 6543
  prepared_statements: false
  pool: 5
  timeout: 5000